### ISSUE TITLE
remove weird line break in opening section

### ISSUE THREAD

**Issue by IanMulvany** [rich-context-competition/rich-context-book-2019#17]
```
that

challenged computer scientists
```

should be replaced by

```
that challenged computer scientists
```

**Comment by dogrdon** [comment]
Yes, still an issue in later compile - in introduction: 


1. C. F. Camerer et al., Evaluating the replicability of social science experiments in Nature  								and Science between 2010 and 2015. Nat. Hum. Behav. 2, 637 (2018). 2. A. Dafoe, Science deserves better: the imperative to share complete replication files. PS  								Polit. Sci. Polit. 47, 60–66 (2014). 3. J. P. A. Ioannidis, Why Most Published Research Findings Are False. PLoS Med. 2, e124

Note: issue box here strips white space, but in chapter there is the line break issue.

**Comment by IanMulvany** [comment]
I think this is resolved now.
